= Mule DevKit
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Web has introduced thousands of new applications for business, IT, collaboration, social media, e-commerce and productivity. Many Web apps expose web APIs to integrate and automate the use of these applications and the data they manage.

Mule includes many connectors that make it easy to connect a Mule application to an external APIs. However, you might require connectivity to an application API that is not currently in Mule's arsenal. Therefore, we introduced the *Mule DevKit* to enable developers to build their own connectors.

In addition to creating connectors, the DevKit can help you build transformers, filters, transports, and much more.

== Where should I start?

Review xref:devkit-overview.adoc[DevKit Overview], then get starting by building xref:your-first-cloud-connector.adoc[Your First Cloud Connector].

== Need Help?

If you need help while developing your Cloud Connector, visit the http://forums.mulesoft.com/[MuleSoft Forums] and post your question to the community.

== Reference Guide

Use the navigation tree in the left sidebar to explore documentation for the Mule DevKit. The materials in the list below are particularly relevant to new users.

* xref:writing-mule-extensions.adoc[Writing Mule Extensions] explains how to code, document, and package Mule extensions using the Mule DevKit.
* xref:publish.adoc[Publish] explains how to share Mule extensions with the Mule community.
* xref:contribute.adoc[Contribute] explains how the Community can help improve the Mule DevKit. The Mule DevKit project source code is open to the entire Mule Community.
* xref:how-the-devkit-works.adoc[How the DevKit Works] provides in-depth information about the Mule DevKit.
* xref:devkit-glossary.adoc[DevKit Glossary] defines key terms used in the Mule DevKit documentation.