= No Authentication
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: devkit, authentication

include::partial$devkit-important.adoc[]

When a connector does not use authentiation, you can use `@Connector` with `@Configuration`.

`@Configuration` adds a set of `@Configurable` fields to your connector as a connector configuration.

== Prerequisites

This document assumes you are familiar with the xref:index.adoc[Anypoint Connector DevKit] and you are ready to implement a configuration in your connector.

== @Configuration Annotation

To implement a `@Configuration` on your Connector, create a new class and annotate it with @Configuration.

The following table describes the parameters for the `@Configuration` annotation:

[%header,cols="4*a"]
|===
|Parameter |Description |Required? |Default Value
|*friendlyName* |Defines the name that is going to be displayed in the connector configuration pop up. |✓
|*configElementName* |Defines the name for the configuration  that is going to be used in the mule app. |  |config
|===

== Example

Ensure these instance variables have public getters and setters (not shown).

[source,java,linenums]
----
@Connector(name = "connector")
public class MyConnector
{
   @ConnectionStrategy
   private ConnectorConfiguration strategy;

/**
 * Processors
 */
}

@Configuration(friendlyName="Foo Configuration")
public class ConnectorConfiguration
{
   @Configurable
   private String property;

   @Configurable
   private String anotherProperty;
}
----