= Promoting Your Module
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you create a new extension, you can create a project on Git. You can share it with the Mule community so you can get feedback on the quality and design of the module before putting it into production. By submitting to a GitHub site, you get the benefit of others trying out your module, and others get the benefit of your work.

Just as you may have made use of the available Mule extensions created by others, the extension you create can help others.

== Submitting Extensions

To help make Mule extensions available to the Mule community, create a readme page on your GitHub site with as many details as possible. This helps people search for Mule extensions and helps them decide if your extension is right for their needs.

Include a link to the source code repository and to the documentation for your extension. The documentation should be as complete as possible to help users start using your extension.